#!/usr/bin/python

import sys
import requests
import time
import os
import math


if len(sys.argv) > 1 :
    if sys.argv[1] == 'config' :
        print 'graph_title API response time'
        print 'graph_vlabel seconds'
        print 'time.label request'
else:
    try :
        r = requests.get('https://localhost.songhi.com/melody-match-server/do?version=1&msg_type_id=7&json_payload=%7B%22uid%22:%22d14096123fe6a33ee5a73746%22%7D&sig=71129494437577dde9151a16a639cedb690d9164')
        if r.status_code != 200 :
            print 'time.value -1'
        else: 
            print 'time.value ' + str(r.elapsed.seconds)
    except :
        print 'time.value -1'

