#!/usr/bin/python

import sys
import requests
import time
import os
import math


if len(sys.argv) > 1 :
    if sys.argv[1] == 'config' :
        print 'graph_title API response time'
        print 'graph_vlabel seconds'
        print 'time.label request'
else:
    try :
        r = requests.get('https://magic-loadtest.songhi.com/melody-match-server/do?version=1.0&sig=ignoredignoredignored&msg_type_id=13&json_payload={%20%22auth_token%22%20:%20%22ignored%22,%20%22uid%22:%20%22testFBUser1%22,%20%22fb_data%22%20:%20[%20{%20%22platform_id%22%20:%201%20},%20{%20%22platform_user_id%22%20:%20%22testFBUser1%22%20},%20{%20%22platform_first_name%22%20:%20%22testFBUser1Name%22%20},%20{%20%22platform_profile_image_url%22%20:%20%22http://ignored.com/img/testFBUser1Im.jpg%22%20},%20{%20%22platform_friends_ids%22%20:%20[%20%22testFBUser1%22,%20%22testFBUser2%22%20]%20}%20]%20}')
        if r.status_code != 200 :
            print 'time.value -1'
        else: 
            print 'time.value ' + str(r.elapsed)
    except :
        print 'time.value -1'

