#!/usr/bin/python

import sys
import requests
import os
import math
import json


try :
    r = requests.get('http://localhost:8080/melody-match-server/status', timeout=3)
    j = json.loads(r.content.replace("'", "\""))
    if j['ok'] == 'true' :
        print 'OK, version: ' + j['version']
        sys.exit(0)
    else :
        print 'Critical: http://localhost:8080/melody-match-server/status did not responded ok'
        sys.exit(2)

except Exception as e:
    print 'Critical: http://localhost:8080/melody-match-server/status timed out'
    sys.exit(2)



